apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: jiwon-tech
data:
  SPRING_PROFILES_ACTIVE: "local"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-service:8761/eureka/"
  TZ: "Asia/Seoul"
  JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"

