apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: jiwon-tech
type: Opaque
stringData:
  # Docker로 PostgreSQL 실행 시 사용
  SPRING_DATASOURCE_URL: "jdbc:postgresql://host.docker.internal:5432/jiwon"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: jiwon-tech
type: Opaque
stringData:
  JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"


