apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: jiwon-tech
data:
  SPRING_PROFILES_ACTIVE: "prod"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-service:8761/eureka/"
  TZ: "Asia/Seoul"


